<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Detail</name>
   <tag></tag>
   <elementGuidId>d72641ca-7cbd-45c7-abf5-55ecc48c6d33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='55']/div/div[3]/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#55 > div.v-card.v-sheet.theme--light > div.v-card__actions.d-block > div.mt-3 > button.button-beli.v-btn.v-btn--outlined.theme--light.v-size--small.primary--text > span.v-btn__content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;13&quot;]/div/div[3]/div[2]/button[1][count(. | //*[(text() = 'Detail' or . = 'Detail')]) = count(//*[(text() = 'Detail' or . = 'Detail')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0703d1d-1247-4e69-a241-d038c5c6c866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>839c7282-c592-4943-8776-a7c8b2714413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>e320914c-e181-4ec5-b3b5-8893afa9def9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;13&quot;]/div/div[3]/div[2]/button[1]</value>
      <webElementGuid>92f1c2ae-5fc1-47b0-9719-0af029bbd213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='55']/div/div[3]/div[2]/button/span</value>
      <webElementGuid>76a585e5-2e42-460f-a500-3e5d0872589b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[35]/preceding::span[3]</value>
      <webElementGuid>be590fa2-93d3-4f3b-881f-0167f2075471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sony PS5'])[24]/preceding::span[4]</value>
      <webElementGuid>1b438d1b-7087-4a77-9a31-fc5faed0edab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[35]/div/div[3]/div[2]/button/span</value>
      <webElementGuid>eaaa2b79-dd9d-4f71-8134-bbcd5265c367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>d288d537-aab7-4a24-be48-4ac9e19b6c43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
