<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_gaming</name>
   <tag></tag>
   <elementGuidId>b8f0bb49-4ddd-4fe9-bb7e-ce132b09c43b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-290-21']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-item-290-21 > div.v-list-item__content > div.v-list-item__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df9d9668-5475-4188-b229-58a0f47bda47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__title</value>
      <webElementGuid>e0a5bc7e-d793-4c23-a6cd-c39637f43261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gaming</value>
      <webElementGuid>5689284d-de95-46e4-afe4-754965ee6626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-290-21&quot;)/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;v-list-item__title&quot;]</value>
      <webElementGuid>63b62fb3-4a1f-46fa-a82c-93d62136513d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-290-21']/div/div</value>
      <webElementGuid>6e76b43c-0362-400f-8f4e-4e466998e5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[18]/following::div[3]</value>
      <webElementGuid>31ac025d-1e8f-4722-9cb5-bfffb5620844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[17]/following::div[6]</value>
      <webElementGuid>b10076c2-95a7-4c58-a346-0f2d4ec30a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[20]/preceding::div[1]</value>
      <webElementGuid>4a658ff0-8e30-493a-9b8e-f6cab76d5e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='game'])[1]/preceding::div[4]</value>
      <webElementGuid>7c19aff2-0aeb-48ff-9dce-bcb4a19e310c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[22]/div/div</value>
      <webElementGuid>b2558d32-cd93-4dc9-8d4a-7c71067e9218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'gaming' or . = 'gaming')]</value>
      <webElementGuid>d51ac608-bd96-47e6-97c5-0951428c9db2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
